### 3.2

In [1]:
import pandas as pd

In [2]:
P=[["A", 130, 1.9, 16.3],
    ["B", 250, 2.6, 10.2],
    ["C", 190, 2.2, 11.1],
    ["D", 300, 2.9, 7.1],
    ["F", 220, 2.3, 13.2],
    ["G",170, 2.2, 14.2]]

print(P)

[['A', 130, 1.9, 16.3], ['B', 250, 2.6, 10.2], ['C', 190, 2.2, 11.1], ['D', 300, 2.9, 7.1], ['F', 220, 2.3, 13.2], ['G', 170, 2.2, 14.2]]

In [3]:
df = pd.DataFrame(P)
df

   0    1    2     3
0  A  130  1.9  16.3
1  B  250  2.6  10.2
2  C  190  2.2  11.1
3  D  300  2.9   7.1
4  F  220  2.3  13.2
5  G  170  2.2  14.2

#### 1) 데이터 프레임 출력

In [4]:
# columns 명칭 지정
df.columns=['Name','HP','Weight','Efficiency']
df

  Name   HP  Weight  Efficiency
0    A  130     1.9        16.3
1    B  250     2.6        10.2
2    C  190     2.2        11.1
3    D  300     2.9         7.1
4    F  220     2.3        13.2
5    G  170     2.2        14.2

#### 2) name 열 인덱스 지정 출력

In [5]:
#index를 Name으로 지정
df.set_index('Name',inplace=True)
df

       HP  Weight  Efficiency
Name
A     130     1.9        16.3
B     250     2.6        10.2
C     190     2.2        11.1
D     300     2.9         7.1
F     220     2.3        13.2
G     170     2.2        14.2

#### 3) 마력과 연비를 곱한 값이 가장 큰 차종 출력

In [6]:
df['HP*Efficiency']=df['HP']*df['Efficiency']
display(df)

       HP  Weight  Efficiency  HP*Efficiency
Name
A     130     1.9        16.3         2119.0
B     250     2.6        10.2         2550.0
C     190     2.2        11.1         2109.0
D     300     2.9         7.1         2130.0
F     220     2.3        13.2         2904.0
G     170     2.2        14.2         2414.0

In [7]:
df['HP*Efficiency'].idxmax()

'F'

#### 행과 열 변환

In [8]:
df.transpose()
df

       HP  Weight  Efficiency  HP*Efficiency
Name
A     130     1.9        16.3         2119.0
B     250     2.6        10.2         2550.0
C     190     2.2        11.1         2109.0
D     300     2.9         7.1         2130.0
F     220     2.3        13.2         2904.0
G     170     2.2        14.2         2414.0